<?php

use Mwg\Controller\ControllerFooter;
use Mwg\Core\Template;

global $_GENERAL;
$sTemplate = Template::getTemplate();

$oFooter      = new ControllerFooter();
$sFooter      = $oFooter->render();

$sTermsOfUse = '<ol>
                    <li>I agree that this site uses cookies, and I allow ' .$_GENERAL['project_name']. ' to store data on my machine.</li>
                    <li>I understand that all the workouts and training methods generated by should be faced just as an suggestion, that means that you will be doing it by your own risk. Furthermore we encourage ' .$_GENERAL['project_name']. ' user to perform these workout under supervision of a certified Physical Education professional.</li>
                </ol>';

$sPageContent = '
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="jumbotron">
                            <div class="container">
                                <h1 class="display-4">Terms of Use</h1>
                                    '.$sTermsOfUse.'
                                <a href="home" class="btn btn-primary">Go Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>';

$sTemplate = str_replace('##page_content##', $sPageContent, $sTemplate);
$sTemplate = str_replace('##page_footer##' , $sFooter     , $sTemplate);

echo $sTemplate;

?>
    